// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use safe_drive::msg::*;
use safe_drive::rcl;
use safe_drive::msg::common_interfaces::*;

extern "C" {
    fn my_interfaces__msg__MyMsgStr__init(msg: *mut MyMsgStr) -> bool;
    fn my_interfaces__msg__MyMsgStr__fini(msg: *mut MyMsgStr);
    fn my_interfaces__msg__MyMsgStr__Sequence__init(msg: *mut MyMsgStrSeqRaw, size: usize) -> bool;
    fn my_interfaces__msg__MyMsgStr__Sequence__fini(msg: *mut MyMsgStrSeqRaw);
    fn rosidl_typesupport_c__get_message_type_support_handle__my_interfaces__msg__MyMsgStr() -> *const rcl::rosidl_message_type_support_t;
}


#[repr(C)]
#[derive(Debug)]
pub struct MyMsgStr {
    pub message: safe_drive::msg::RosString<0>,
    pub static_array_str: [safe_drive::msg::RosString<0>; 2],
    pub dynamic_array_str: safe_drive::msg::RosStringSeq<0, 0>,
    pub bounded_array_str: safe_drive::msg::RosStringSeq<0, 3>,
    pub bounded_str: safe_drive::msg::RosString<10>,
    pub static_array_bounded_str: [safe_drive::msg::RosString<10>; 2],
    pub dynamic_array_bounded_str: safe_drive::msg::RosStringSeq<10, 0>,
    pub bounded_array_bounded_str: safe_drive::msg::RosStringSeq<10, 3>,
}

impl MyMsgStr {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { my_interfaces__msg__MyMsgStr__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for MyMsgStr {
    fn drop(&mut self) {
        unsafe { my_interfaces__msg__MyMsgStr__fini(self) };
    }
}

#[repr(C)]
#[derive(Debug)]
struct MyMsgStrSeqRaw {
    data: *mut MyMsgStr,
    size: usize,
    capacity: usize,
}

/// Sequence of MyMsgStr.
/// `N` is the maximum number of elements.
/// If `N` is `0`, the size is unlimited.
#[repr(C)]
#[derive(Debug)]
pub struct MyMsgStrSeq<const N: usize> {
    data: *mut MyMsgStr,
    size: usize,
    capacity: usize,
}

impl<const N: usize> MyMsgStrSeq<N> {
    /// Create a sequence of.
    /// `N` represents the maximum number of elements.
    /// If `N` is `0`, the sequence is unlimited.
    pub fn new(size: usize) -> Option<Self> {
        if N != 0 && size >= N {
            // the size exceeds in the maximum number
            return None;
        }

        let mut msg: MyMsgStrSeqRaw = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { my_interfaces__msg__MyMsgStr__Sequence__init(&mut msg, size) } {
            Some(Self {data: msg.data, size: msg.size, capacity: msg.capacity })
        } else {
            None
        }
    }

    pub fn as_slice(&self) -> Option<&[MyMsgStr]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            Some(s)
        }
    }

    pub fn as_slice_mut(&mut self) -> Option<&mut [MyMsgStr]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            Some(s)
        }
    }
}

impl<const N: usize> Drop for MyMsgStrSeq<N> {
    fn drop(&mut self) {
        let mut msg = MyMsgStrSeqRaw{data: self.data, size: self.size, capacity: self.capacity};
        unsafe { my_interfaces__msg__MyMsgStr__Sequence__fini(&mut msg) };
    }
}

unsafe impl<const N: usize> Send for MyMsgStrSeq<N> {}
unsafe impl<const N: usize> Sync for MyMsgStrSeq<N> {}


impl TopicMsg for MyMsgStr {
    fn type_support() -> *const rcl::rosidl_message_type_support_t {
        unsafe {
            rosidl_typesupport_c__get_message_type_support_handle__my_interfaces__msg__MyMsgStr()
        }
    }
}
