// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use safe_drive::msg::*;
use safe_drive::rcl;
use safe_drive::msg::common_interfaces::*;

extern "C" {
    fn my_interfaces__msg__MyMsgs__init(msg: *mut MyMsgs) -> bool;
    fn my_interfaces__msg__MyMsgs__fini(msg: *mut MyMsgs);
    fn my_interfaces__msg__MyMsgs__Sequence__init(msg: *mut MyMsgsSeqRaw, size: usize) -> bool;
    fn my_interfaces__msg__MyMsgs__Sequence__fini(msg: *mut MyMsgsSeqRaw);
    fn rosidl_typesupport_c__get_message_type_support_handle__my_interfaces__msg__MyMsgs() -> *const rcl::rosidl_message_type_support_t;
}


#[repr(C)]
#[derive(Debug)]
pub struct MyMsgs {
    pub msg1: MyMsg,
    pub msg2: MyMsg,
}

impl MyMsgs {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { my_interfaces__msg__MyMsgs__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for MyMsgs {
    fn drop(&mut self) {
        unsafe { my_interfaces__msg__MyMsgs__fini(self) };
    }
}

#[repr(C)]
#[derive(Debug)]
struct MyMsgsSeqRaw {
    data: *mut MyMsgs,
    size: usize,
    capacity: usize,
}

/// Sequence of MyMsgs.
/// `N` is the maximum number of elements.
/// If `N` is `0`, the size is unlimited.
#[repr(C)]
#[derive(Debug)]
pub struct MyMsgsSeq<const N: usize> {
    data: *mut MyMsgs,
    size: usize,
    capacity: usize,
}

impl<const N: usize> MyMsgsSeq<N> {
    /// Create a sequence of.
    /// `N` represents the maximum number of elements.
    /// If `N` is `0`, the sequence is unlimited.
    pub fn new(size: usize) -> Option<Self> {
        if N != 0 && size >= N {
            // the size exceeds in the maximum number
            return None;
        }

        let mut msg: MyMsgsSeqRaw = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { my_interfaces__msg__MyMsgs__Sequence__init(&mut msg, size) } {
            Some(Self {data: msg.data, size: msg.size, capacity: msg.capacity })
        } else {
            None
        }
    }

    pub fn as_slice(&self) -> Option<&[MyMsgs]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            Some(s)
        }
    }

    pub fn as_slice_mut(&mut self) -> Option<&mut [MyMsgs]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            Some(s)
        }
    }
}

impl<const N: usize> Drop for MyMsgsSeq<N> {
    fn drop(&mut self) {
        let mut msg = MyMsgsSeqRaw{data: self.data, size: self.size, capacity: self.capacity};
        unsafe { my_interfaces__msg__MyMsgs__Sequence__fini(&mut msg) };
    }
}

unsafe impl<const N: usize> Send for MyMsgsSeq<N> {}
unsafe impl<const N: usize> Sync for MyMsgsSeq<N> {}


impl TopicMsg for MyMsgs {
    fn type_support() -> *const rcl::rosidl_message_type_support_t {
        unsafe {
            rosidl_typesupport_c__get_message_type_support_handle__my_interfaces__msg__MyMsgs()
        }
    }
}
