version: '3'
services:
  safe_drive_tutorial:
    build:
      context: .
    stdin_open: true
    tty: true
    working_dir: "/safe_drive_tutorial"
    environment:
      - DISPLAY=$DISPLAY
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - PULSE_SERVER=$PULSE_SERVER
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - "../:/safe_drive_tutorial"
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
    runtime: nvidia
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
