version: '3'
services:
  safe_drive_tutorial:
    build:
      context: .
    stdin_open: true
    tty: true
    working_dir: "/safe_drive_tutorial"
    volumes:
      - "../:/safe_drive_tutorial"
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
